image: hiroyukionaka/pandoc-viola-savepdf-ja:latest

clone:
  lfs: true

pipelines:
  default:
      - step:
          script:
            - rm -rf target
            - mkdir -p target
            - bash ./build.sh
            - bash ./deploy.sh
